Jul-12 17:21:37.182 [main] DEBUG nextflow.cli.Launcher - $> nextflow run download_databases.nf -profile conda --download_all -c nextflow_slurm.config
Jul-12 17:21:37.299 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 23.04.3
Jul-12 17:21:37.316 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/Drives/O/USERS/gwajnber/.nextflow/plugins; core-plugins: nf-amazon@1.16.2,nf-azure@1.0.1,nf-codecommit@0.1.4,nf-console@1.0.5,nf-ga4gh@1.0.5,nf-google@1.7.3,nf-tower@1.5.12,nf-wave@0.8.4
Jul-12 17:21:37.334 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Jul-12 17:21:37.336 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Jul-12 17:21:37.339 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Jul-12 17:21:37.349 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Jul-12 17:21:37.364 [main] DEBUG nextflow.config.ConfigBuilder - Found config local: /Drives/O/USERS/gwajnber/mob-rgi-nf/nextflow.config
Jul-12 17:21:37.368 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /Drives/O/USERS/gwajnber/mob-rgi-nf/nextflow_slurm.config
Jul-12 17:21:37.368 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /Drives/O/USERS/gwajnber/mob-rgi-nf/nextflow.config
Jul-12 17:21:37.368 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /Drives/O/USERS/gwajnber/mob-rgi-nf/nextflow_slurm.config
Jul-12 17:21:37.386 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `conda`
Jul-12 17:21:37.955 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `conda`
Jul-12 17:21:38.075 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [conda, docker]
Jul-12 17:21:38.108 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 by global default
Jul-12 17:21:38.131 [main] INFO  nextflow.cli.CmdRun - Launching `download_databases.nf` [golden_shannon] DSL2 - revision: ab60c8e560
Jul-12 17:21:38.132 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Jul-12 17:21:38.132 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Jul-12 17:21:38.141 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /Drives/O/USERS/gwajnber/.nextflow/secrets/store.json
Jul-12 17:21:38.144 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@176f7f3b] - activable => nextflow.secret.LocalSecretsProvider@176f7f3b
Jul-12 17:21:38.204 [main] DEBUG nextflow.Session - Session UUID: 933f0a15-e15f-46d5-80cd-bbe49532fa46
Jul-12 17:21:38.205 [main] DEBUG nextflow.Session - Run name: golden_shannon
Jul-12 17:21:38.206 [main] DEBUG nextflow.Session - Executor pool size: 144
Jul-12 17:21:38.216 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=432; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Jul-12 17:21:38.274 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 23.04.3 build 5875
  Created: 11-08-2023 18:37 UTC (13:37 CDT)
  System: Linux 3.10.0-1160.88.1.el7.x86_64
  Runtime: Groovy 3.0.16 on OpenJDK 64-Bit Server VM 17.0.6+10
  Encoding: UTF-8 (ANSI_X3.4-1968)
  Process: 318094@waffles-g-3.cscscience.ca [10.10.20.32]
  CPUs: 144 - Mem: 1007.1 GB (197.7 GB) - Swap: 4 GB (0)
Jul-12 17:21:38.330 [main] DEBUG nextflow.Session - Work-dir: /Drives/O/USERS/gwajnber/mob-rgi-nf/work [nfs]
Jul-12 17:21:38.365 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Jul-12 17:21:38.378 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Jul-12 17:21:38.413 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Jul-12 17:21:38.425 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 145; maxThreads: 1000
Jul-12 17:21:38.589 [main] DEBUG nextflow.Session - Session start
Jul-12 17:21:38.974 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jul-12 17:21:38.985 [main] INFO  nextflow.Nextflow - 

Download Databases
-------------------
MOB-suite databases: true
CARD json: true


Jul-12 17:21:39.004 [main] INFO  nextflow.script.BaseScript - Downloading CARD json file, please wait
Jul-12 17:21:39.041 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:RGI` matches labels `RGI` for process with name download_CARD_WF:download_CARD_json
Jul-12 17:21:39.052 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: slurm
Jul-12 17:21:39.053 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'slurm'
Jul-12 17:21:39.062 [main] DEBUG nextflow.executor.Executor - [warm up] executor > slurm
Jul-12 17:21:39.066 [main] DEBUG n.processor.TaskPollingMonitor - Creating task monitor for executor 'slurm' > capacity: 2000; pollInterval: 5s; dumpInterval: 5m 
Jul-12 17:21:39.068 [main] DEBUG n.processor.TaskPollingMonitor - Creating submit rate limit of 10 submissions per 1 seconds
Jul-12 17:21:39.071 [main] DEBUG n.executor.AbstractGridExecutor - Creating executor 'slurm' > queue-stat-interval: 1m
Jul-12 17:21:39.134 [main] INFO  nextflow.script.BaseScript - Downloading MOB-suite databases, please wait
Jul-12 17:21:39.136 [main] DEBUG nextflow.script.ProcessConfig - Config settings `withLabel:MOB` matches labels `MOB` for process with name download_MOB_WF:download_MOB_database
Jul-12 17:21:39.137 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: slurm
Jul-12 17:21:39.137 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'slurm'
Jul-12 17:21:39.141 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: download_CARD_WF:download_CARD_json, download_CARD_json, download_MOB_database, download_MOB_WF:download_MOB_database
Jul-12 17:21:39.141 [main] DEBUG nextflow.Session - Igniting dataflow network (2)
Jul-12 17:21:39.141 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > download_CARD_WF:download_CARD_json
Jul-12 17:21:39.142 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > download_MOB_WF:download_MOB_database
Jul-12 17:21:39.142 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Jul-12 17:21:39.142 [main] DEBUG nextflow.Session - Session await
Jul-12 17:21:39.240 [Actor Thread 9] INFO  nextflow.conda.CondaCache - Creating env using mamba: bioconda::mob_suite=3.1.4 [cache /Drives/O/USERS/gwajnber/mob-rgi-nf/work/conda/env-a4015aef2c4a1441b149485a3d827b84]
Jul-12 17:21:39.247 [Actor Thread 10] INFO  nextflow.conda.CondaCache - Creating env using mamba: bioconda::rgi [cache /Drives/O/USERS/gwajnber/mob-rgi-nf/work/conda/env-d03a114db9a9924558d68864492ba208]
Jul-12 17:21:56.389 [Actor Thread 6] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=download_CARD_WF:download_CARD_json; work-dir=null
  error [java.lang.IllegalStateException]: java.lang.IllegalStateException: Failed to create Conda environment
  command: mamba create --mkdir --yes --quiet --prefix /Drives/O/USERS/gwajnber/mob-rgi-nf/work/conda/env-d03a114db9a9924558d68864492ba208 bioconda::rgi
  status : 1
  message:
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/09cdf8bf.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/ffeee55f.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/2a957770.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/ffeee55f.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/2a957770.json" was modified by another program
    Could not read JSON repodata file (/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json) parse error line 1
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
            return func(*args, **kwargs)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
            raise e
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
            exit_code = _wrapped_main(*args, **kwargs)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
            result = do_call(parsed_args, p)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 758, in do_call
            exit_code = create(args, parser)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 632, in create
            return install(args, parser, "create")
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 499, in install
            index = load_channels(pool, channels, repos)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 178, in load_channels
            repo = subdir.create_repo(pool)
        RuntimeError: Could not read JSON repodata file (/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json) parse error line 1
    
    `$ /Drives/O/USERS/gwajnber/mambaforge/bin/mamba create --mkdir --yes --quiet --prefix /Drives/O/USERS/gwajnber/mob-rgi-nf/work/conda/env-d03a114db9a9924558d68864492ba208 bioconda::rgi`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/Drives/O/USERS/gwajnber/mambaforge/bin/conda
                 CONDA_PREFIX=/Drives/O/USERS/gwajnber/mambaforge
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/Drives/O/USERS/gwajnber/mambaforge/bin/python
                   CONDA_ROOT=/Drives/O/USERS/gwajnber/mambaforge
                  CONDA_SHLVL=1
               CURL_CA_BUNDLE=<not set>
           DRMAA_LIBRARY_PATH=/usr/local/lib/libdrmaa.so.1
         JAVA_LD_LIBRARY_PATH=/Drives/O/USERS/gwajnber/mambaforge/lib/jvm/lib/server
                   LD_PRELOAD=<not set>
                      MANPATH=:/opt/puppetlabs/puppet/share/man
                   MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                         PATH=/Drives/O/USERS/gwajnber/.sdkman/candidates/java/current/bin:/Drives/O
                              /USERS/gwajnber/mambaforge/bin:/Drives/O/USERS/gwajnber/mambaforge/con
                              dabin:/opt/miniconda3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr
                              /sbin:/opt/puppetlabs/bin:/Drives/O/USERS/gwajnber/.local/bin:/Drives/
                              O/USERS/gwajnber/bin
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : base
        active env location : /Drives/O/USERS/gwajnber/mambaforge
                shell level : 1
           user config file : /Drives/O/USERS/gwajnber/.condarc
     populated config files : /Drives/O/USERS/gwajnber/mambaforge/.condarc
                              /Drives/O/USERS/gwajnber/.condarc
              conda version : 23.3.1
        conda-build version : 3.21.9
             python version : 3.10.12.final.0
           virtual packages : __archspec=1=x86_64
                              __glibc=2.17=0
                              __linux=3.10.0=0
                              __unix=0=0
           base environment : /Drives/O/USERS/gwajnber/mambaforge  (writable)
          conda av data dir : /Drives/O/USERS/gwajnber/mambaforge/etc/conda
      conda av metadata url : None
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
              package cache : /Drives/O/USERS/gwajnber/mambaforge/pkgs
                              /Drives/O/USERS/gwajnber/.conda/pkgs
           envs directories : /Drives/O/USERS/gwajnber/mambaforge/envs
                              /Drives/O/USERS/gwajnber/.conda/envs
                   platform : linux-64
                 user-agent : conda/23.3.1 requests/2.32.3 CPython/3.10.12 Linux/3.10.0-1160.88.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                    UID:GID : 103317:105393
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.

Jul-12 17:21:56.441 [Actor Thread 6] ERROR nextflow.processor.TaskProcessor - Error executing process > 'download_CARD_WF:download_CARD_json'

Caused by:
  Failed to create Conda environment
  command: mamba create --mkdir --yes --quiet --prefix /Drives/O/USERS/gwajnber/mob-rgi-nf/work/conda/env-d03a114db9a9924558d68864492ba208 bioconda::rgi
  status : 1
  message:
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/09cdf8bf.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/ffeee55f.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/2a957770.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/ffeee55f.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/2a957770.json" was modified by another program
    Could not read JSON repodata file (/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json) parse error line 1
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
            return func(*args, **kwargs)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
            raise e
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
            exit_code = _wrapped_main(*args, **kwargs)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
            result = do_call(parsed_args, p)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 758, in do_call
            exit_code = create(args, parser)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 632, in create
            return install(args, parser, "create")
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 499, in install
            index = load_channels(pool, channels, repos)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 178, in load_channels
            repo = subdir.create_repo(pool)
        RuntimeError: Could not read JSON repodata file (/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json) parse error line 1
    
    `$ /Drives/O/USERS/gwajnber/mambaforge/bin/mamba create --mkdir --yes --quiet --prefix /Drives/O/USERS/gwajnber/mob-rgi-nf/work/conda/env-d03a114db9a9924558d68864492ba208 bioconda::rgi`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/Drives/O/USERS/gwajnber/mambaforge/bin/conda
                 CONDA_PREFIX=/Drives/O/USERS/gwajnber/mambaforge
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/Drives/O/USERS/gwajnber/mambaforge/bin/python
                   CONDA_ROOT=/Drives/O/USERS/gwajnber/mambaforge
                  CONDA_SHLVL=1
               CURL_CA_BUNDLE=<not set>
           DRMAA_LIBRARY_PATH=/usr/local/lib/libdrmaa.so.1
         JAVA_LD_LIBRARY_PATH=/Drives/O/USERS/gwajnber/mambaforge/lib/jvm/lib/server
                   LD_PRELOAD=<not set>
                      MANPATH=:/opt/puppetlabs/puppet/share/man
                   MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                         PATH=/Drives/O/USERS/gwajnber/.sdkman/candidates/java/current/bin:/Drives/O
                              /USERS/gwajnber/mambaforge/bin:/Drives/O/USERS/gwajnber/mambaforge/con
                              dabin:/opt/miniconda3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr
                              /sbin:/opt/puppetlabs/bin:/Drives/O/USERS/gwajnber/.local/bin:/Drives/
                              O/USERS/gwajnber/bin
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : base
        active env location : /Drives/O/USERS/gwajnber/mambaforge
                shell level : 1
           user config file : /Drives/O/USERS/gwajnber/.condarc
     populated config files : /Drives/O/USERS/gwajnber/mambaforge/.condarc
                              /Drives/O/USERS/gwajnber/.condarc
              conda version : 23.3.1
        conda-build version : 3.21.9
             python version : 3.10.12.final.0
           virtual packages : __archspec=1=x86_64
                              __glibc=2.17=0
                              __linux=3.10.0=0
                              __unix=0=0
           base environment : /Drives/O/USERS/gwajnber/mambaforge  (writable)
          conda av data dir : /Drives/O/USERS/gwajnber/mambaforge/etc/conda
      conda av metadata url : None
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
              package cache : /Drives/O/USERS/gwajnber/mambaforge/pkgs
                              /Drives/O/USERS/gwajnber/.conda/pkgs
           envs directories : /Drives/O/USERS/gwajnber/mambaforge/envs
                              /Drives/O/USERS/gwajnber/.conda/envs
                   platform : linux-64
                 user-agent : conda/23.3.1 requests/2.32.3 CPython/3.10.12 Linux/3.10.0-1160.88.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                    UID:GID : 103317:105393
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.


java.lang.IllegalStateException: java.lang.IllegalStateException: Failed to create Conda environment
  command: mamba create --mkdir --yes --quiet --prefix /Drives/O/USERS/gwajnber/mob-rgi-nf/work/conda/env-d03a114db9a9924558d68864492ba208 bioconda::rgi
  status : 1
  message:
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/09cdf8bf.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/ffeee55f.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/2a957770.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/ffeee55f.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/2a957770.json" was modified by another program
    Could not read JSON repodata file (/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json) parse error line 1
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
            return func(*args, **kwargs)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
            raise e
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
            exit_code = _wrapped_main(*args, **kwargs)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
            result = do_call(parsed_args, p)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 758, in do_call
            exit_code = create(args, parser)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 632, in create
            return install(args, parser, "create")
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 499, in install
            index = load_channels(pool, channels, repos)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 178, in load_channels
            repo = subdir.create_repo(pool)
        RuntimeError: Could not read JSON repodata file (/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json) parse error line 1
    
    `$ /Drives/O/USERS/gwajnber/mambaforge/bin/mamba create --mkdir --yes --quiet --prefix /Drives/O/USERS/gwajnber/mob-rgi-nf/work/conda/env-d03a114db9a9924558d68864492ba208 bioconda::rgi`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/Drives/O/USERS/gwajnber/mambaforge/bin/conda
                 CONDA_PREFIX=/Drives/O/USERS/gwajnber/mambaforge
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/Drives/O/USERS/gwajnber/mambaforge/bin/python
                   CONDA_ROOT=/Drives/O/USERS/gwajnber/mambaforge
                  CONDA_SHLVL=1
               CURL_CA_BUNDLE=<not set>
           DRMAA_LIBRARY_PATH=/usr/local/lib/libdrmaa.so.1
         JAVA_LD_LIBRARY_PATH=/Drives/O/USERS/gwajnber/mambaforge/lib/jvm/lib/server
                   LD_PRELOAD=<not set>
                      MANPATH=:/opt/puppetlabs/puppet/share/man
                   MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                         PATH=/Drives/O/USERS/gwajnber/.sdkman/candidates/java/current/bin:/Drives/O
                              /USERS/gwajnber/mambaforge/bin:/Drives/O/USERS/gwajnber/mambaforge/con
                              dabin:/opt/miniconda3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr
                              /sbin:/opt/puppetlabs/bin:/Drives/O/USERS/gwajnber/.local/bin:/Drives/
                              O/USERS/gwajnber/bin
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : base
        active env location : /Drives/O/USERS/gwajnber/mambaforge
                shell level : 1
           user config file : /Drives/O/USERS/gwajnber/.condarc
     populated config files : /Drives/O/USERS/gwajnber/mambaforge/.condarc
                              /Drives/O/USERS/gwajnber/.condarc
              conda version : 23.3.1
        conda-build version : 3.21.9
             python version : 3.10.12.final.0
           virtual packages : __archspec=1=x86_64
                              __glibc=2.17=0
                              __linux=3.10.0=0
                              __unix=0=0
           base environment : /Drives/O/USERS/gwajnber/mambaforge  (writable)
          conda av data dir : /Drives/O/USERS/gwajnber/mambaforge/etc/conda
      conda av metadata url : None
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
              package cache : /Drives/O/USERS/gwajnber/mambaforge/pkgs
                              /Drives/O/USERS/gwajnber/.conda/pkgs
           envs directories : /Drives/O/USERS/gwajnber/mambaforge/envs
                              /Drives/O/USERS/gwajnber/.conda/envs
                   platform : linux-64
                 user-agent : conda/23.3.1 requests/2.32.3 CPython/3.10.12 Linux/3.10.0-1160.88.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                    UID:GID : 103317:105393
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.

	at nextflow.conda.CondaCache.getCachePathFor(CondaCache.groovy:378)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:166)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:69)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.processor.TaskRun.getCondaEnv0(TaskRun.groovy:596)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at nextflow.processor.TaskRun$_getCondaEnv_closure5.doCall(TaskRun.groovy:588)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:112)
	at jdk.proxy1/jdk.proxy1.$Proxy29.apply(Unknown Source)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:198)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:51)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at nextflow.processor.TaskRun.getCondaEnv(TaskRun.groovy:588)
	at nextflow.processor.TaskRun$getCondaEnv$11.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at nextflow.processor.TaskProcessor.createTaskHashKey(TaskProcessor.groovy:2097)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:48)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:189)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:57)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:617)
	at nextflow.processor.InvokeTaskAdapter.call(InvokeTaskAdapter.groovy:52)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Failed to create Conda environment
  command: mamba create --mkdir --yes --quiet --prefix /Drives/O/USERS/gwajnber/mob-rgi-nf/work/conda/env-d03a114db9a9924558d68864492ba208 bioconda::rgi
  status : 1
  message:
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/09cdf8bf.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/ffeee55f.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/2a957770.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/ffeee55f.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/2a957770.json" was modified by another program
    Could not read JSON repodata file (/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json) parse error line 1
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
            return func(*args, **kwargs)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
            raise e
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
            exit_code = _wrapped_main(*args, **kwargs)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
            result = do_call(parsed_args, p)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 758, in do_call
            exit_code = create(args, parser)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 632, in create
            return install(args, parser, "create")
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 499, in install
            index = load_channels(pool, channels, repos)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 178, in load_channels
            repo = subdir.create_repo(pool)
        RuntimeError: Could not read JSON repodata file (/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json) parse error line 1
    
    `$ /Drives/O/USERS/gwajnber/mambaforge/bin/mamba create --mkdir --yes --quiet --prefix /Drives/O/USERS/gwajnber/mob-rgi-nf/work/conda/env-d03a114db9a9924558d68864492ba208 bioconda::rgi`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/Drives/O/USERS/gwajnber/mambaforge/bin/conda
                 CONDA_PREFIX=/Drives/O/USERS/gwajnber/mambaforge
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/Drives/O/USERS/gwajnber/mambaforge/bin/python
                   CONDA_ROOT=/Drives/O/USERS/gwajnber/mambaforge
                  CONDA_SHLVL=1
               CURL_CA_BUNDLE=<not set>
           DRMAA_LIBRARY_PATH=/usr/local/lib/libdrmaa.so.1
         JAVA_LD_LIBRARY_PATH=/Drives/O/USERS/gwajnber/mambaforge/lib/jvm/lib/server
                   LD_PRELOAD=<not set>
                      MANPATH=:/opt/puppetlabs/puppet/share/man
                   MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                         PATH=/Drives/O/USERS/gwajnber/.sdkman/candidates/java/current/bin:/Drives/O
                              /USERS/gwajnber/mambaforge/bin:/Drives/O/USERS/gwajnber/mambaforge/con
                              dabin:/opt/miniconda3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr
                              /sbin:/opt/puppetlabs/bin:/Drives/O/USERS/gwajnber/.local/bin:/Drives/
                              O/USERS/gwajnber/bin
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : base
        active env location : /Drives/O/USERS/gwajnber/mambaforge
                shell level : 1
           user config file : /Drives/O/USERS/gwajnber/.condarc
     populated config files : /Drives/O/USERS/gwajnber/mambaforge/.condarc
                              /Drives/O/USERS/gwajnber/.condarc
              conda version : 23.3.1
        conda-build version : 3.21.9
             python version : 3.10.12.final.0
           virtual packages : __archspec=1=x86_64
                              __glibc=2.17=0
                              __linux=3.10.0=0
                              __unix=0=0
           base environment : /Drives/O/USERS/gwajnber/mambaforge  (writable)
          conda av data dir : /Drives/O/USERS/gwajnber/mambaforge/etc/conda
      conda av metadata url : None
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
              package cache : /Drives/O/USERS/gwajnber/mambaforge/pkgs
                              /Drives/O/USERS/gwajnber/.conda/pkgs
           envs directories : /Drives/O/USERS/gwajnber/mambaforge/envs
                              /Drives/O/USERS/gwajnber/.conda/envs
                   platform : linux-64
                 user-agent : conda/23.3.1 requests/2.32.3 CPython/3.10.12 Linux/3.10.0-1160.88.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                    UID:GID : 103317:105393
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.

	at nextflow.conda.CondaCache.runCommand(CondaCache.groovy:327)
	at nextflow.conda.CondaCache.createLocalCondaEnv0(CondaCache.groovy:299)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1258)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1036)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1019)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
	at nextflow.conda.CondaCache$_createLocalCondaEnv_closure1.doCall(CondaCache.groovy:256)
	at nextflow.conda.CondaCache$_createLocalCondaEnv_closure1.call(CondaCache.groovy)
	at nextflow.file.FileMutex.lock(FileMutex.groovy:106)
	at nextflow.conda.CondaCache.createLocalCondaEnv(CondaCache.groovy:256)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1258)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1036)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1019)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
	at nextflow.conda.CondaCache$_getLazyImagePath_closure3.doCall(CondaCache.groovy:355)
	at nextflow.conda.CondaCache$_getLazyImagePath_closure3.call(CondaCache.groovy)
	at groovyx.gpars.dataflow.LazyDataflowVariable$1.run(LazyDataflowVariable.java:70)
	... 3 common frames omitted
Jul-12 17:21:56.448 [Actor Thread 6] DEBUG nextflow.Session - Session aborted -- Cause: java.lang.IllegalStateException: Failed to create Conda environment
  command: mamba create --mkdir --yes --quiet --prefix /Drives/O/USERS/gwajnber/mob-rgi-nf/work/conda/env-d03a114db9a9924558d68864492ba208 bioconda::rgi
  status : 1
  message:
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/09cdf8bf.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/ffeee55f.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/2a957770.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/ffeee55f.json" was modified by another program
    warning  libmamba Cache file "/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/2a957770.json" was modified by another program
    Could not read JSON repodata file (/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json) parse error line 1
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
            return func(*args, **kwargs)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
            raise e
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
            exit_code = _wrapped_main(*args, **kwargs)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
            result = do_call(parsed_args, p)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 758, in do_call
            exit_code = create(args, parser)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 632, in create
            return install(args, parser, "create")
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 499, in install
            index = load_channels(pool, channels, repos)
          File "/Drives/O/USERS/gwajnber/mambaforge/lib/python3.10/site-packages/mamba/utils.py", line 178, in load_channels
            repo = subdir.create_repo(pool)
        RuntimeError: Could not read JSON repodata file (/Drives/O/USERS/gwajnber/mambaforge/pkgs/cache/497deca9.json) parse error line 1
    
    `$ /Drives/O/USERS/gwajnber/mambaforge/bin/mamba create --mkdir --yes --quiet --prefix /Drives/O/USERS/gwajnber/mob-rgi-nf/work/conda/env-d03a114db9a9924558d68864492ba208 bioconda::rgi`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/Drives/O/USERS/gwajnber/mambaforge/bin/conda
                 CONDA_PREFIX=/Drives/O/USERS/gwajnber/mambaforge
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/Drives/O/USERS/gwajnber/mambaforge/bin/python
                   CONDA_ROOT=/Drives/O/USERS/gwajnber/mambaforge
                  CONDA_SHLVL=1
               CURL_CA_BUNDLE=<not set>
           DRMAA_LIBRARY_PATH=/usr/local/lib/libdrmaa.so.1
         JAVA_LD_LIBRARY_PATH=/Drives/O/USERS/gwajnber/mambaforge/lib/jvm/lib/server
                   LD_PRELOAD=<not set>
                      MANPATH=:/opt/puppetlabs/puppet/share/man
                   MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                         PATH=/Drives/O/USERS/gwajnber/.sdkman/candidates/java/current/bin:/Drives/O
                              /USERS/gwajnber/mambaforge/bin:/Drives/O/USERS/gwajnber/mambaforge/con
                              dabin:/opt/miniconda3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr
                              /sbin:/opt/puppetlabs/bin:/Drives/O/USERS/gwajnber/.local/bin:/Drives/
                              O/USERS/gwajnber/bin
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : base
        active env location : /Drives/O/USERS/gwajnber/mambaforge
                shell level : 1
           user config file : /Drives/O/USERS/gwajnber/.condarc
     populated config files : /Drives/O/USERS/gwajnber/mambaforge/.condarc
                              /Drives/O/USERS/gwajnber/.condarc
              conda version : 23.3.1
        conda-build version : 3.21.9
             python version : 3.10.12.final.0
           virtual packages : __archspec=1=x86_64
                              __glibc=2.17=0
                              __linux=3.10.0=0
                              __unix=0=0
           base environment : /Drives/O/USERS/gwajnber/mambaforge  (writable)
          conda av data dir : /Drives/O/USERS/gwajnber/mambaforge/etc/conda
      conda av metadata url : None
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
              package cache : /Drives/O/USERS/gwajnber/mambaforge/pkgs
                              /Drives/O/USERS/gwajnber/.conda/pkgs
           envs directories : /Drives/O/USERS/gwajnber/mambaforge/envs
                              /Drives/O/USERS/gwajnber/.conda/envs
                   platform : linux-64
                 user-agent : conda/23.3.1 requests/2.32.3 CPython/3.10.12 Linux/3.10.0-1160.88.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                    UID:GID : 103317:105393
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.

Jul-12 17:21:56.469 [Actor Thread 6] DEBUG nextflow.Session - The following nodes are still active:
[process] download_CARD_WF:download_CARD_json
  status=ACTIVE
  port 0: (cntrl) -     ; channel: $

[process] download_MOB_WF:download_MOB_database
  status=ACTIVE
  port 0: (cntrl) -     ; channel: $

Jul-12 17:21:56.471 [main] DEBUG nextflow.Session - Session await > all processes finished
Jul-12 17:21:56.471 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jul-12 17:21:56.473 [Actor Thread 2] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=download_MOB_WF:download_MOB_database; work-dir=null
  error [java.lang.InterruptedException]: java.lang.InterruptedException
Jul-12 17:21:56.473 [Actor Thread 1] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=download_CARD_WF:download_CARD_json; work-dir=null
  error [java.lang.InterruptedException]: java.lang.InterruptedException
Jul-12 17:21:56.480 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=0; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=0ms; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=0; peakCpus=0; peakMemory=0; ]
Jul-12 17:21:56.841 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Jul-12 17:21:56.878 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
